import type { Video, Celebrity, Movie } from './types';

// ============================================
// Mock Videos
// ============================================
export const mockVideos: Video[] = [
    {
        id: '11111111-1111-1111-1111-111111111111',
        raw_video_id: null,
        title: { en: 'Scarlett Johansson Nude Scene in Under the Skin', ru: 'Скарлетт Йоханссон обнажённая сцена в Побудь в моей шкуре' },
        slug: { en: 'scarlett-johansson-under-the-skin', ru: 'skarlett-johansson-pobud-v-moej-shkure' },
        review: {},
        seo_title: {},
        seo_description: {},
        original_title: 'Under the Skin',
        quality: 'HD',
        duration_seconds: 185,
        duration_formatted: '3:05',
        video_url: null,
        video_url_watermarked: null,
        thumbnail_url: null,
        preview_gif_url: null,
        screenshots: [],
        sprite_url: null,
        sprite_data: null,
        ai_model: null,
        ai_confidence: null,
        ai_raw_response: null,
        enrichment_layers_used: null,
        views_count: 125400,
        likes_count: 3420,
        dislikes_count: 45,
        status: 'published',
        published_at: '2026-02-28T12:00:00Z',
        created_at: '2026-02-28T10:00:00Z',
        updated_at: '2026-02-28T12:00:00Z',
        celebrities: [{ id: 1, name: 'Scarlett Johansson', slug: 'scarlett-johansson', name_localized: { en: 'Scarlett Johansson', ru: 'Скарлетт Йоханссон' }, aliases: [], bio: {}, photo_url: null, photo_local: null, birth_date: '1984-11-22', nationality: 'American', tmdb_id: 1245, imdb_id: 'nm0424060', external_ids: {}, videos_count: 8, movies_count: 5, avg_rating: 4.5, total_views: 450000, is_featured: true, ai_matched: true, created_at: '', updated_at: '' }],
    },
    {
        id: '22222222-2222-2222-2222-222222222222',
        raw_video_id: null,
        title: { en: 'Margot Robbie Nude Scene in The Wolf of Wall Street', ru: 'Марго Робби обнажённая сцена в Волк с Уолл-стрит' },
        slug: { en: 'margot-robbie-wolf-wall-street', ru: 'margo-robbi-volk-s-uoll-strit' },
        review: {},
        seo_title: {},
        seo_description: {},
        original_title: 'The Wolf of Wall Street',
        quality: 'HD',
        duration_seconds: 240,
        duration_formatted: '4:00',
        video_url: null,
        video_url_watermarked: null,
        thumbnail_url: null,
        preview_gif_url: null,
        screenshots: [],
        sprite_url: null,
        sprite_data: null,
        ai_model: null,
        ai_confidence: null,
        ai_raw_response: null,
        enrichment_layers_used: null,
        views_count: 98700,
        likes_count: 2800,
        dislikes_count: 32,
        status: 'published',
        published_at: '2026-02-27T12:00:00Z',
        created_at: '2026-02-27T10:00:00Z',
        updated_at: '2026-02-27T12:00:00Z',
        celebrities: [{ id: 2, name: 'Margot Robbie', slug: 'margot-robbie', name_localized: { en: 'Margot Robbie', ru: 'Марго Робби' }, aliases: [], bio: {}, photo_url: null, photo_local: null, birth_date: '1990-07-02', nationality: 'Australian', tmdb_id: 234352, imdb_id: 'nm3053338', external_ids: {}, videos_count: 6, movies_count: 4, avg_rating: 4.3, total_views: 380000, is_featured: true, ai_matched: true, created_at: '', updated_at: '' }],
    },
    {
        id: '33333333-3333-3333-3333-333333333333',
        raw_video_id: null,
        title: { en: 'Emilia Clarke Nude Scene in Game of Thrones', ru: 'Эмилия Кларк обнажённая сцена в Игре престолов' },
        slug: { en: 'emilia-clarke-game-of-thrones', ru: 'emiliya-klark-igra-prestolov' },
        review: {},
        seo_title: {},
        seo_description: {},
        original_title: 'Game of Thrones',
        quality: 'HD',
        duration_seconds: 312,
        duration_formatted: '5:12',
        video_url: null,
        video_url_watermarked: null,
        thumbnail_url: null,
        preview_gif_url: null,
        screenshots: [],
        sprite_url: null,
        sprite_data: null,
        ai_model: null,
        ai_confidence: null,
        ai_raw_response: null,
        enrichment_layers_used: null,
        views_count: 245000,
        likes_count: 5100,
        dislikes_count: 67,
        status: 'published',
        published_at: '2026-02-26T12:00:00Z',
        created_at: '2026-02-26T10:00:00Z',
        updated_at: '2026-02-26T12:00:00Z',
        celebrities: [{ id: 3, name: 'Emilia Clarke', slug: 'emilia-clarke', name_localized: { en: 'Emilia Clarke', ru: 'Эмилия Кларк' }, aliases: [], bio: {}, photo_url: null, photo_local: null, birth_date: '1986-10-23', nationality: 'British', tmdb_id: 1223786, imdb_id: 'nm3592338', external_ids: {}, videos_count: 12, movies_count: 3, avg_rating: 4.7, total_views: 890000, is_featured: true, ai_matched: true, created_at: '', updated_at: '' }],
    },
    {
        id: '44444444-4444-4444-4444-444444444444',
        raw_video_id: null,
        title: { en: 'Alexandra Daddario in True Detective', ru: 'Александра Даддарио в Настоящем детективе' },
        slug: { en: 'alexandra-daddario-true-detective', ru: 'aleksandra-daddario-nastoyashchij-detektiv' },
        review: {},
        seo_title: {},
        seo_description: {},
        original_title: 'True Detective',
        quality: 'HD',
        duration_seconds: 156,
        duration_formatted: '2:36',
        video_url: null,
        video_url_watermarked: null,
        thumbnail_url: null,
        preview_gif_url: null,
        screenshots: [],
        sprite_url: null,
        sprite_data: null,
        ai_model: null,
        ai_confidence: null,
        ai_raw_response: null,
        enrichment_layers_used: null,
        views_count: 567000,
        likes_count: 8900,
        dislikes_count: 120,
        status: 'published',
        published_at: '2026-02-25T12:00:00Z',
        created_at: '2026-02-25T10:00:00Z',
        updated_at: '2026-02-25T12:00:00Z',
        celebrities: [{ id: 4, name: 'Alexandra Daddario', slug: 'alexandra-daddario', name_localized: { en: 'Alexandra Daddario', ru: 'Александра Даддарио' }, aliases: [], bio: {}, photo_url: null, photo_local: null, birth_date: '1986-03-16', nationality: 'American', tmdb_id: 20536, imdb_id: 'nm1275259', external_ids: {}, videos_count: 5, movies_count: 4, avg_rating: 4.8, total_views: 920000, is_featured: true, ai_matched: true, created_at: '', updated_at: '' }],
    },
    {
        id: '55555555-5555-5555-5555-555555555555',
        raw_video_id: null,
        title: { en: 'Sydney Sweeney in Euphoria', ru: 'Сидни Суини в Эйфории' },
        slug: { en: 'sydney-sweeney-euphoria', ru: 'sidni-suini-ejforiya' },
        review: {},
        seo_title: {},
        seo_description: {},
        original_title: 'Euphoria',
        quality: 'HD',
        duration_seconds: 198,
        duration_formatted: '3:18',
        video_url: null,
        video_url_watermarked: null,
        thumbnail_url: null,
        preview_gif_url: null,
        screenshots: [],
        sprite_url: null,
        sprite_data: null,
        ai_model: null,
        ai_confidence: null,
        ai_raw_response: null,
        enrichment_layers_used: null,
        views_count: 432000,
        likes_count: 7200,
        dislikes_count: 89,
        status: 'published',
        published_at: '2026-02-24T12:00:00Z',
        created_at: '2026-02-24T10:00:00Z',
        updated_at: '2026-02-24T12:00:00Z',
        celebrities: [{ id: 5, name: 'Sydney Sweeney', slug: 'sydney-sweeney', name_localized: { en: 'Sydney Sweeney', ru: 'Сидни Суини' }, aliases: [], bio: {}, photo_url: null, photo_local: null, birth_date: '1997-09-12', nationality: 'American', tmdb_id: 1397778, imdb_id: 'nm4991344', external_ids: {}, videos_count: 7, movies_count: 3, avg_rating: 4.6, total_views: 678000, is_featured: true, ai_matched: true, created_at: '', updated_at: '' }],
    },
    {
        id: '66666666-6666-6666-6666-666666666666',
        raw_video_id: null,
        title: { en: 'Ana de Armas Nude Scene in Blonde', ru: 'Ана де Армас обнажённая сцена в Блондинке' },
        slug: { en: 'ana-de-armas-blonde', ru: 'ana-de-armas-blondinka' },
        review: {},
        seo_title: {},
        seo_description: {},
        original_title: 'Blonde',
        quality: 'HD',
        duration_seconds: 274,
        duration_formatted: '4:34',
        video_url: null,
        video_url_watermarked: null,
        thumbnail_url: null,
        preview_gif_url: null,
        screenshots: [],
        sprite_url: null,
        sprite_data: null,
        ai_model: null,
        ai_confidence: null,
        ai_raw_response: null,
        enrichment_layers_used: null,
        views_count: 312000,
        likes_count: 5600,
        dislikes_count: 78,
        status: 'published',
        published_at: '2026-02-23T12:00:00Z',
        created_at: '2026-02-23T10:00:00Z',
        updated_at: '2026-02-23T12:00:00Z',
        celebrities: [{ id: 6, name: 'Ana de Armas', slug: 'ana-de-armas', name_localized: { en: 'Ana de Armas', ru: 'Ана де Армас' }, aliases: [], bio: {}, photo_url: null, photo_local: null, birth_date: '1988-04-30', nationality: 'Cuban-Spanish', tmdb_id: 224513, imdb_id: 'nm1869101', external_ids: {}, videos_count: 4, movies_count: 3, avg_rating: 4.4, total_views: 345000, is_featured: true, ai_matched: true, created_at: '', updated_at: '' }],
    },
];

// ============================================
// Mock Celebrities
// ============================================
export const mockCelebrities: Celebrity[] = [
    { id: 1, name: 'Scarlett Johansson', slug: 'scarlett-johansson', name_localized: { en: 'Scarlett Johansson', ru: 'Скарлетт Йоханссон' }, aliases: [], bio: {}, photo_url: null, photo_local: null, birth_date: '1984-11-22', nationality: 'American', tmdb_id: 1245, imdb_id: 'nm0424060', external_ids: {}, videos_count: 8, movies_count: 5, avg_rating: 4.5, total_views: 450000, is_featured: true, ai_matched: true, created_at: '', updated_at: '' },
    { id: 2, name: 'Margot Robbie', slug: 'margot-robbie', name_localized: { en: 'Margot Robbie', ru: 'Марго Робби' }, aliases: [], bio: {}, photo_url: null, photo_local: null, birth_date: '1990-07-02', nationality: 'Australian', tmdb_id: 234352, imdb_id: 'nm3053338', external_ids: {}, videos_count: 6, movies_count: 4, avg_rating: 4.3, total_views: 380000, is_featured: true, ai_matched: true, created_at: '', updated_at: '' },
    { id: 3, name: 'Emilia Clarke', slug: 'emilia-clarke', name_localized: { en: 'Emilia Clarke', ru: 'Эмилия Кларк' }, aliases: [], bio: {}, photo_url: null, photo_local: null, birth_date: '1986-10-23', nationality: 'British', tmdb_id: 1223786, imdb_id: 'nm3592338', external_ids: {}, videos_count: 12, movies_count: 3, avg_rating: 4.7, total_views: 890000, is_featured: true, ai_matched: true, created_at: '', updated_at: '' },
    { id: 4, name: 'Alexandra Daddario', slug: 'alexandra-daddario', name_localized: { en: 'Alexandra Daddario', ru: 'Александра Даддарио' }, aliases: [], bio: {}, photo_url: null, photo_local: null, birth_date: '1986-03-16', nationality: 'American', tmdb_id: 20536, imdb_id: 'nm1275259', external_ids: {}, videos_count: 5, movies_count: 4, avg_rating: 4.8, total_views: 920000, is_featured: true, ai_matched: true, created_at: '', updated_at: '' },
    { id: 5, name: 'Sydney Sweeney', slug: 'sydney-sweeney', name_localized: { en: 'Sydney Sweeney', ru: 'Сидни Суини' }, aliases: [], bio: {}, photo_url: null, photo_local: null, birth_date: '1997-09-12', nationality: 'American', tmdb_id: 1397778, imdb_id: 'nm4991344', external_ids: {}, videos_count: 7, movies_count: 3, avg_rating: 4.6, total_views: 678000, is_featured: true, ai_matched: true, created_at: '', updated_at: '' },
    { id: 6, name: 'Ana de Armas', slug: 'ana-de-armas', name_localized: { en: 'Ana de Armas', ru: 'Ана де Армас' }, aliases: [], bio: {}, photo_url: null, photo_local: null, birth_date: '1988-04-30', nationality: 'Cuban-Spanish', tmdb_id: 224513, imdb_id: 'nm1869101', external_ids: {}, videos_count: 4, movies_count: 3, avg_rating: 4.4, total_views: 345000, is_featured: true, ai_matched: true, created_at: '', updated_at: '' },
    { id: 7, name: 'Elizabeth Olsen', slug: 'elizabeth-olsen', name_localized: { en: 'Elizabeth Olsen', ru: 'Элизабет Олсен' }, aliases: [], bio: {}, photo_url: null, photo_local: null, birth_date: '1989-02-16', nationality: 'American', tmdb_id: 17, imdb_id: 'nm0647634', external_ids: {}, videos_count: 3, movies_count: 2, avg_rating: 4.2, total_views: 210000, is_featured: true, ai_matched: true, created_at: '', updated_at: '' },
    { id: 8, name: 'Florence Pugh', slug: 'florence-pugh', name_localized: { en: 'Florence Pugh', ru: 'Флоренс Пью' }, aliases: [], bio: {}, photo_url: null, photo_local: null, birth_date: '1996-01-03', nationality: 'British', tmdb_id: 1373737, imdb_id: 'nm6073955', external_ids: {}, videos_count: 5, movies_count: 3, avg_rating: 4.1, total_views: 289000, is_featured: true, ai_matched: true, created_at: '', updated_at: '' },
];

// ============================================
// Mock Movies
// ============================================
export const mockMovies: Movie[] = [
    { id: 1, title: 'Under the Skin', title_localized: { en: 'Under the Skin', ru: 'Побудь в моей шкуре' }, slug: 'under-the-skin', year: 2013, poster_url: null, poster_local: null, description: {}, studio: 'Film4', director: 'Jonathan Glazer', genres: ['Sci-Fi', 'Drama'], tmdb_id: 97057, imdb_id: 'tt1441395', external_ids: {}, scenes_count: 3, total_views: 125000, ai_matched: true, created_at: '', updated_at: '' },
    { id: 2, title: 'The Wolf of Wall Street', title_localized: { en: 'The Wolf of Wall Street', ru: 'Волк с Уолл-стрит' }, slug: 'wolf-of-wall-street', year: 2013, poster_url: null, poster_local: null, description: {}, studio: 'Paramount', director: 'Martin Scorsese', genres: ['Biography', 'Comedy', 'Crime'], tmdb_id: 106646, imdb_id: 'tt0993846', external_ids: {}, scenes_count: 5, total_views: 234000, ai_matched: true, created_at: '', updated_at: '' },
    { id: 3, title: 'Game of Thrones', title_localized: { en: 'Game of Thrones', ru: 'Игра престолов' }, slug: 'game-of-thrones', year: 2011, poster_url: null, poster_local: null, description: {}, studio: 'HBO', director: 'Various', genres: ['Drama', 'Fantasy'], tmdb_id: 1399, imdb_id: 'tt0944947', external_ids: {}, scenes_count: 45, total_views: 890000, ai_matched: true, created_at: '', updated_at: '' },
    { id: 4, title: 'Blonde', title_localized: { en: 'Blonde', ru: 'Блондинка' }, slug: 'blonde', year: 2022, poster_url: null, poster_local: null, description: {}, studio: 'Netflix', director: 'Andrew Dominik', genres: ['Biography', 'Drama'], tmdb_id: 597208, imdb_id: 'tt1655420', external_ids: {}, scenes_count: 8, total_views: 456000, ai_matched: true, created_at: '', updated_at: '' },
];
